### ISSUE TITLE
Does not seem to support API version 2019-10

### ISSUE THREAD

**Issue by LouiseEH** [mikeyhew/shopify_graphql_client#11]
Error message:
GraphQL::Client::ValidationError (Field 'bulkOperationRunQuery' doesn't exist on type 'Mutation'):

It seems the graphql path is without the version, which I think gives the oldest supported version.
Maybe the version can be included by replacing the line:

uri.path = "/admin/api/graphql.json" 

in ShopifyGraphQLClient with

ShopifyAPI::Base.api_version.construct_graphql_path

**Comment by mikeyhew** [comment]
Sure, that sounds reasonable. Can you open a pull request with that change, and check that it fixes the issue for you?

**Comment by LouiseEH** [comment]
I can try that, although I am not quite sure how to do it, as I am new to rails:

1. Download the repository
2. Run bin/setup
3. Make the above suggested code changes
4. SHOP_DOMAIN=myshop OAUTH_TOKEN=... bin/update_schema
5. bundle exec rake install
But how do I then use the local gem in the project I am currently working on, in order to test it? Maybe step 5 gives me a gem name I can add to the Gemfile of the other project?

Maybe there are more issues related to the versioning of the API?:
I think it must be possible for each developer using the gem to update the schema, as one developer might be using the 2019-10 version and another the 2020-01 version.
I am not sure whether that's possible in the current setup, but it sounds like you have to download the repository in order to be able to update the schema?

**Comment by mikeyhew** [comment]
That's a good point, when I built this I didn't think about how each API version will have a different schema.

It probably makes sense to let developers use their own schema file, without having to use their own fork of the gem, because they may want to work with the unstable version which is always changing. It might be helpful to provide the stable versions out of the box, but that's also extra maintenance work.

I'm not working on any Shopify apps these days, so I'm going to mark this repo as unmaintained. You're welcome to fork it and do what you want with it. Hopefully things will be improved upstream in https://github.com/shopify/shopify_api so that this project can become obsolete.

**Comment by mikeyhew** [comment]
Closing since this repo is unmaintained. Good luck!

**Comment by LouiseEH** [comment]
FYI: for anybody else looking for a way to call Shopifys graphql API, there's a recent active PR on the shopify_api gem

**Comment by resistorsoftware** [comment]
I found it useful to simply include the schema I want in the fork I choose to use. Seems reasonable for now
